### ISSUE TITLE
Release Source Code

### ISSUE THREAD

**Issue by wilgaboury** [TiagoCavalcante/solid-colorful#2]
Is there going to be a source code release of this tool?

**Comment by TiagoCavalcante** [comment]
Hi @wilgaboury I release the source code of every library I have, but I have lost the source code of this :cry:
I have released this library with a wrong config, so only dist stuff got into NPM (in truth everything in this repo is from NPM)

**Comment by wilgaboury** [comment]
I'm sorry to hear that you lost the source code
